# Main doc: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions
# Runners spec: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
# Glob expressions: https://github.com/actions/toolkit/tree/main/packages/glob

name: Windows tests

###############################################################################
# Schedule:
# Push on main branch
###############################################################################
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

###############################################################################
# Platform script options shared among all jobs
###############################################################################
env:
  COQREGTESTING: y

###############################################################################
# Builds Windows installer
###############################################################################
jobs:
  Windows_platform:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - '32'
          - '64'

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          
      - name: Git checkout install scripts
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Git checkout Coq platform
        uses: actions/checkout@v2
        with:
          repository: coq/platform
          path: platform

      - name: Run common platform script
        shell: cmd
        run: platform\coq_platform_make_windows.bat -destcyg=C:\cygwin_coq_platform -arch=${{matrix.architecture}} -extent=b -parallel=p -jobs=2 -vst=n -compcert=n
          
      - name: Install packages specified in cfg file
        shell: cmd
        run: |
          xcopy main C:\cygwin_coq_platform\home\runneradmin\coq-platform /e /s /y
          C:\cygwin_coq_platform\bin\bash --login -c "cd coq-platform && ./install_packages.sh test_files/packages.cfg"
        
      - name: Patch SerAPI
        shell: cmd
        run: |
          copy main\patch_serapi.sh C:\cygwin_coq_platform\home\runneradmin\
          C:\cygwin_coq_platform\bin\bash --login -c "./patch_serapi.sh"
         
      - name: Create installer
        shell: cmd
        run: C:\cygwin_coq_platform\bin\bash --login -c "cd coq-platform/ && windows/create_installer_windows.sh && mkdir /cygdrive/c/installer && cp windows_installer/*exe /cygdrive/c/installer/"

      - name: Run test file
        shell: cmd
        run: C:\cygwin_coq_platform\bin\bash --login -c "cd coq-platform/ && ./test.sh"
